### ISSUE TITLE
 0.2.0 zip file broken?

### ISSUE THREAD

**Issue by GrantCarter** [bossanova808/repository.bossanova808#10]
Is it just me or is the 0.2.0 zip file broken.

and https://kodi.wiki/view/Unofficial_add-on_repositories needs updating

**Comment by bossanova808** [comment]
Well that's odd.  Git could not detect any changes, and the zip was unzipping fine lcoally, but indeed not when downloaded off github.  So I rebuilt the zip, force pushed it, and tested the new zip - works ok for me now.  Also, updated the wiki link.  Thanks for the report.
