### ISSUE TITLE
repository.bossanova808-master will not install on Kodi 18.4/ macos 10.14.6

### ISSUE THREAD

**Issue by BeastOfBodmin** [bossanova808/repository.bossanova808#12]
I couldn't find out how to create a .zip file Kodi repository from this code tree, so I chose "download ZIP" from this page

https://github.com/bossanova808/repository.bossanova808

When I pointed Kodi at resulting .zip file, I got the following 

`2019-11-04 22:17:10.059 T:4655449536   ERROR: Failed to read 'zip://%2fUsers%2fadam%2fdmg%2frepository.bossanova808-master.zip/repository.bossanova808-master/addon.xml'
2019-11-04 22:19:04.031 T:4655449536   ERROR: Previous line repeats 1 times.
`

Can you please tell me what are the steps to get this installed?

**Comment by bossanova808** [comment]
As per:
https://kodi.wiki/view/Unofficial_add-on_repositories

https://github.com/bossanova808/repository.bossanova808/raw/master/repository-downloads/repository.bossanova808/repository.bossanova808-0.2.0.zip
