### ISSUE TITLE
Addentional Time for passthrough

### ISSUE THREAD

**Issue by Newan** [bossanova808/repository.bossanova808#6]
Every time on Start "Device not ready or busy" on Line 328-331
`                   #for debugging, grab the process output....
                    output, result = subprocess.Popen(exe, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell=False).communicate()
                    log("$$$$$$$$$$$$$$$ " + str(output))
                    log("$$$$$$$$$$$$$$$ " + str(result))
`
My solution is to add an sleep at line. 318, 2 seconds:

`
            logNotice ("Attempting to start player: " + str(exe))
            logNotice ("Path is: " + str(sys.path))
            logNotice ("Waitung for Output Device")
            time.sleep(2)
`

Now it works perfect

**Comment by bossanova808** [comment]
Can you move lines 255-258
```
    #pause
    if constants.SECONDS_TO_PAUSE_STARTUP!=0:
        logNotice("Pausing for " + str(constants.SECONDS_TO_PAUSE_STARTUP) + ", per request in XSqueeze settings.")
        notify("Pausing for " + str(constants.SECONDS_TO_PAUSE_STARTUP) + " seconds.", "(per request in XSqueeze settings.)")
        time.sleep(constants.SECONDS_TO_PAUSE_STARTUP)
```

to later around 280 so it looks like:

```
        #are we running the locally installed Squeezeslave?
        if constants.PLAYBACK:

            #set up for actual playback - suspend AE as it can hog the audio device
            xbmcAudioSuspended = False
            playInit()

            #pause
            if constants.SECONDS_TO_PAUSE_STARTUP!=0:
                logNotice("Pausing for " + str(constants.SECONDS_TO_PAUSE_STARTUP) + ", per request in XSqueeze settings.")
                notify("Pausing for " + str(constants.SECONDS_TO_PAUSE_STARTUP) + " seconds.", "(per request in XSqueeze settings.)")
                time.sleep(constants.SECONDS_TO_PAUSE_STARTUP)

```

I think that pause is fine to move later in the process to be honest, and avoids the need for yet another pause.

Try that and let me know how it works.

**Comment by Newan** [comment]
sorry for the late answer, little bit busy ...

i moved it to line 280 and add :
`<setting id="startuppause" value="2" />`
to my settings.xml.

It works!

**Comment by bossanova808** [comment]
Changed & pushed.  Glad we got there!

Hopefully it works well for you now!
