### ISSUE TITLE
No radio tab in skin.confluence.bossanova808.krypton-0.0.6

### ISSUE THREAD

**Issue by ceptic** [bossanova808/repository.bossanova808#8]
Jeremy,
Great weather addon and confluence skin however since I upgraded to Libreelec 8.0.2 and skin.confluence.bossanova808.krypton-0.0.6 I no longer have the FTA Radio tab. The Radio tab is present in the Kodi repo Confluence but just not in yours.
Chris

**Comment by bossanova808** [comment]
Yeah I don't use radio and it annoys me that it can't be turned off, so I've removed it.  If you want to put it back you'll need to fork the skin....if you want to do a PR that implements the change with a setting, that's fine too, but I personally won't be doing it I'm afraid, very busy right now.
