### ISSUE TITLE
Xsqueeze with 4 speakers

### ISSUE THREAD

**Issue by vjoris** [bossanova808/repository.bossanova808#9]
Hi. I've a Kodi setting with 4 speakers and everything works well. But not the the Xsqueeze add on. The music only is broadcasted over the 2 main speakers. Even if I have stereo up mixing selected. For the youtube plug in, for instance, I hear music on all the for speakers. 
Is there a certain setting that I forgot?

**Comment by bossanova808** [comment]
You'd need to look at the settings for audo output in squeezelite and add whatever you need into the settings area of xsqueeze - the audio setting in Kodi itself play no part in the playback by XSqueeze, which is using squeezelite.

**Comment by bossanova808** [comment]
You'd need to look at the settings for audo output in squeezelite and add whatever you need into the settings area of xsqueeze - the audio setting in Kodi itself play no part in the playback by XSqueeze, which is using squeezelite.

**Comment by bossanova808** [comment]
https://www.max2play.com/en/wiki/command-line-options-for-squeezelite/

**Comment by vjoris** [comment]
Hi bossanova,
Thanks for your quick response. I've checked the link you gave me and although I'm familiar with max2play and the command line options. I don't find (or know) the correct one to use and basically get my plugin more unstable then stable.  So if you know what command to use, it would be of great help.
